currency:
  available:
    - "RUB"
cost:
  rub:
    perKg: 400
    minimal: 350
    perCubicMeter: 12000
    minDistance: 450

geo:
  latitude:
    min: 45
    max: 65
  longitude:
    min: 30
    max: 96